[package]
name = "sd-jwt"
version = "0.7.0"
authors = ["Rob Sliwa <robjsliwa@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "SD-JWT support for Issuers, Holders, and Verifiers"
homepage = "https://github.com/robjsliwa/sd-jwt"
repository = "https://github.com/robjsliwa/sd-jwt"
keywords = ["sd-jwt", "sdjwt", "token", "sd_jwt", "selective disclosure"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.51"
rand = "0.8.5"
base64 = "0.21.5"
sha2 = "0.10.8"
jsonwebtoken = "9.2.0"
chrono = "0.4.31"

[dev-dependencies]
rsa = "0.5"
